# Generated by Django 5.2 on 2025-10-21 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelroom',
            name='dealer',
        ),
    ]
