# Generated by Django 5.2 on 2025-11-02 03:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='support_chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_date', models.DateTimeField()),
                ('TimeDuration', models.DurationField()),
                ('Chat_reference_number', models.CharField(max_length=10, unique=True)),
                ('Chat_status', models.CharField(blank=True, choices=[('pending', 'penging'), ('Resolved', 'Resolved')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
