# Generated by Django 5.2 on 2025-11-02 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_support_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support_chat',
            name='Chat_status',
            field=models.CharField(choices=[('pending', 'penging'), ('Resolved', 'Resolved')], max_length=10),
        ),
    ]
