# Generated by Django 5.2 on 2025-10-29 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_hotelroom_dealer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='from_city',
            new_name='destination',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='to_city',
            new_name='source',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='available_seats',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='dealer',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='total_seats',
        ),
        migrations.AddField(
            model_name='flight',
            name='seats_available',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='flight',
            name='airline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.airline'),
        ),
        migrations.CreateModel(
            name='Flight_Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_name', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('total_price', models.DecimalField(decimal_places=2, default=5000, max_digits=10)),
                ('passengers', models.PositiveIntegerField(default=1)),
                ('booked_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
