# Generated by Django 5.2 on 2025-11-03 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_support_chat_chat_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='airline',
        ),
        migrations.RemoveField(
            model_name='hotelroom',
            name='hotel',
        ),
        migrations.AlterField(
            model_name='booking',
            name='hotel_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hotel'),
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='Hotel_image',
            new_name='hotel_image',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='amenities',
        ),
        migrations.AddField(
            model_name='hotel',
            name='extra_amenities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='hotel',
            name='has_cctv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotel',
            name='has_dining',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotel',
            name='has_elevator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotel',
            name='has_gym',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotel',
            name='has_parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotel',
            name='has_restaurant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotel',
            name='has_room_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotel',
            name='has_swimming_pool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotel',
            name='has_tv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotel',
            name='has_wifi',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='description',
            field=models.TextField(blank=True, help_text='Brief description about the hotel, nearby attractions, etc.', null=True),
        ),
        migrations.DeleteModel(
            name='Airline',
        ),
        migrations.DeleteModel(
            name='Flight',
        ),
        migrations.DeleteModel(
            name='HotelRoom',
        ),
    ]
