# Generated by Django 5.2 on 2025-11-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_flight_airline_remove_hotelroom_hotel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='ac_room_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of air-conditioned rooms.'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='non_ac_room_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of non air-conditioned rooms.'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='number_of_rooms',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
