# Generated by Django 5.2 on 2025-10-29 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_flight_booking_arrival_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight_booking',
            name='seat_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
