# Generated by Django 5.2 on 2025-11-05 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_hotel_ac_room_count_hotel_non_ac_room_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='hotel_room',
            new_name='hotel',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='Booking_id',
        ),
        migrations.AlterField(
            model_name='hotel',
            name='ac_room_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='floor_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='non_ac_room_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='number_of_rooms',
            field=models.PositiveIntegerField(blank=True, help_text='Total number of rooms in the hotel', null=True),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10)),
                ('room_type', models.CharField(choices=[('AC', 'AC Room'), ('NON_AC', 'Non-AC Room')], max_length=10)),
                ('is_booked', models.BooleanField(default=False)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='app.hotel')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.room'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_id',
            field=models.CharField(default=1, editable=False, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
