# Generated by Django 5.2 on 2025-11-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_room_price_alter_room_room_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='booked_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
