# Generated by Django 5.2 on 2025-11-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_room_booked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='number',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
